import { FinancialData, User } from './types';
import { MOCK_EXPENSE_CATEGORIES, MOCK_INCOME_CATEGORIES } from './constants';

export const initialFinancialData: FinancialData = {
    accounts: [
        {
            id: 'acc-checking',
            name: 'Everyday Checking',
            type: 'Checking',
            balance: 2450.75,
            currency: 'EUR',
            financialInstitution: 'Crystal Bank',
            accountNumber: 'BE68 5390 0754 7034',
            routingNumber: 'KREDBEBB',
            openingDate: '2020-03-12',
            icon: 'account_balance',
            isPrimary: true,
        },
        {
            id: 'acc-savings',
            name: 'Rainy Day Savings',
            type: 'Savings',
            balance: 8200.5,
            currency: 'EUR',
            financialInstitution: 'Crystal Bank',
            apy: 1.25,
            openingDate: '2021-06-01',
            linkedAccountId: 'acc-checking',
            icon: 'savings',
        },
        {
            id: 'acc-credit',
            name: 'Aurora Rewards Card',
            type: 'Credit Card',
            balance: -640.22,
            currency: 'EUR',
            financialInstitution: 'Aurora Bank',
            last4: '4242',
            expirationDate: '12/26',
            cardNetwork: 'Visa',
            cardholderName: 'Demo User',
            paymentDate: 25,
            settlementAccountId: 'acc-checking',
            creditLimit: 5000,
            icon: 'credit_card',
        },
        {
            id: 'acc-brokerage',
            name: 'Index Portfolio',
            type: 'Investment',
            subType: 'ETF',
            balance: 12540,
            currency: 'EUR',
            financialInstitution: 'Crystal Invest',
            symbol: 'VWCE',
            icon: 'show_chart',
        },
        {
            id: 'acc-crypto',
            name: 'Digital Assets',
            type: 'Investment',
            subType: 'Crypto',
            balance: 3200,
            currency: 'EUR',
            financialInstitution: 'Ledger Wallet',
            icon: 'currency_bitcoin',
        },
    ],
    transactions: [
        {
            id: 'tx-salary-may',
            accountId: 'acc-checking',
            date: '2024-05-28',
            description: 'Monthly Salary - Crystal Analytics',
            merchant: 'Crystal Analytics',
            amount: 3200,
            category: 'Salary',
            type: 'income',
            currency: 'EUR',
        },
        {
            id: 'tx-rent-jun',
            accountId: 'acc-checking',
            date: '2024-06-01',
            description: 'Apartment Rent',
            merchant: 'Canal View Properties',
            amount: -1200,
            category: 'Rent',
            type: 'expense',
            currency: 'EUR',
        },
        {
            id: 'tx-groceries',
            accountId: 'acc-checking',
            date: '2024-06-03',
            description: 'GreenMart Grocery',
            merchant: 'GreenMart',
            amount: -86.45,
            category: 'Supermarket',
            type: 'expense',
            currency: 'EUR',
        },
        {
            id: 'tx-commute',
            accountId: 'acc-checking',
            date: '2024-06-04',
            description: 'Metro Pass Reload',
            merchant: 'Brussels Metro',
            amount: -49,
            category: 'Public Transport',
            type: 'expense',
            currency: 'EUR',
        },
        {
            id: 'tx-streaming',
            accountId: 'acc-credit',
            date: '2024-05-15',
            description: 'Netflix Subscription',
            merchant: 'Netflix',
            amount: -14.99,
            category: 'Streaming Services',
            type: 'expense',
            currency: 'EUR',
        },
        {
            id: 'tx-streaming-jun',
            accountId: 'acc-credit',
            date: '2024-06-15',
            description: 'Netflix Subscription',
            merchant: 'Netflix',
            amount: -14.99,
            category: 'Streaming Services',
            type: 'expense',
            currency: 'EUR',
        },
        {
            id: 'tx-music',
            accountId: 'acc-credit',
            date: '2024-06-10',
            description: 'Spotify Premium',
            merchant: 'Spotify',
            amount: -9.99,
            category: 'Apps & Software',
            type: 'expense',
            currency: 'EUR',
        },
        {
            id: 'tx-storage',
            accountId: 'acc-credit',
            date: '2024-05-25',
            description: 'CloudDrive 200GB',
            merchant: 'CloudDrive',
            amount: -2.99,
            category: 'Cloud Storage',
            type: 'expense',
            currency: 'EUR',
        },
        {
            id: 'tx-gym',
            accountId: 'acc-checking',
            date: '2024-06-05',
            description: 'FitLife Gym Membership',
            merchant: 'FitLife Gym',
            amount: -39,
            category: 'Fitness / Gym',
            type: 'expense',
            currency: 'EUR',
        },
        {
            id: 'tx-dividend',
            accountId: 'acc-brokerage',
            date: '2024-05-20',
            description: 'ETF Distribution',
            merchant: 'Crystal Invest',
            amount: 45.5,
            category: 'Investments & Dividends',
            type: 'income',
            currency: 'EUR',
        },
        {
            id: 'tx-savings',
            accountId: 'acc-checking',
            date: '2024-06-02',
            description: 'Transfer to Savings',
            merchant: 'Internal Transfer',
            amount: -300,
            category: 'Investments',
            type: 'expense',
            currency: 'EUR',
            transferId: 'tr-savings',
        },
        {
            id: 'tx-savings-in',
            accountId: 'acc-savings',
            date: '2024-06-02',
            description: 'Transfer from Checking',
            merchant: 'Internal Transfer',
            amount: 300,
            category: 'Investments',
            type: 'income',
            currency: 'EUR',
            transferId: 'tr-savings',
        },
        {
            id: 'tx-flight',
            accountId: 'acc-checking',
            date: '2024-05-18',
            description: 'EuroAir Ticket',
            merchant: 'EuroAir',
            amount: -220,
            category: 'Flights',
            type: 'expense',
            currency: 'EUR',
        },
    ],
    investmentTransactions: [
        { id: 'inv-buy-vwce', symbol: 'VWCE', name: 'Vanguard FTSE All-World UCITS', quantity: 10, price: 105.2, date: '2024-04-10', type: 'buy' },
        { id: 'inv-buy-aapl', symbol: 'AAPL', name: 'Apple Inc.', quantity: 5, price: 170, date: '2024-05-05', type: 'buy' },
        { id: 'inv-sell-aapl', symbol: 'AAPL', name: 'Apple Inc.', quantity: 2, price: 182, date: '2024-06-01', type: 'sell' },
        { id: 'inv-buy-btc', symbol: 'BTC', name: 'Bitcoin', quantity: 0.05, price: 65000, date: '2024-03-15', type: 'buy' },
    ],
    recurringTransactions: [
        {
            id: 'sub-netflix',
            accountId: 'acc-credit',
            description: 'Netflix Subscription',
            amount: 14.99,
            category: 'Streaming Services',
            type: 'expense',
            currency: 'EUR',
            frequency: 'monthly',
            startDate: '2024-03-15',
            nextDueDate: '2024-07-15',
            weekendAdjustment: 'after',
            dueDateOfMonth: 15,
        },
        {
            id: 'sub-spotify',
            accountId: 'acc-credit',
            description: 'Spotify Premium',
            amount: 9.99,
            category: 'Apps & Software',
            type: 'expense',
            currency: 'EUR',
            frequency: 'monthly',
            startDate: '2024-02-10',
            nextDueDate: '2024-07-10',
            weekendAdjustment: 'after',
            dueDateOfMonth: 10,
        },
        {
            id: 'sub-clouddrive',
            accountId: 'acc-credit',
            description: 'CloudDrive 200GB',
            amount: 2.99,
            category: 'Cloud Storage',
            type: 'expense',
            currency: 'EUR',
            frequency: 'monthly',
            startDate: '2024-01-25',
            nextDueDate: '2024-06-25',
            weekendAdjustment: 'after',
            dueDateOfMonth: 25,
        },
        {
            id: 'sub-fitlife',
            accountId: 'acc-checking',
            description: 'FitLife Gym Membership',
            amount: 39,
            category: 'Fitness / Gym',
            type: 'expense',
            currency: 'EUR',
            frequency: 'monthly',
            startDate: '2023-11-05',
            nextDueDate: '2024-07-05',
            weekendAdjustment: 'after',
            dueDateOfMonth: 5,
        },
    ],
    recurringTransactionOverrides: [],
    loanPaymentOverrides: {},
    financialGoals: [],
    budgets: [],
    tasks: [],
    warrants: [],
    memberships: [
        {
            id: 'mem-starbrew',
            provider: 'StarBrew Coffee',
            memberId: 'SB-239984',
            tier: 'Gold',
            holderName: 'Demo User',
            memberSince: '2021-04-12',
            points: '1,240 pts',
            expiryDate: '2025-04-30',
            color: '#8B5CF6',
            icon: 'local_cafe',
            notes: 'Free drink coupon every 10 stamps',
            website: 'https://starbrew.example.com',
            category: 'Food & Drink',
        },
        {
            id: 'mem-euroair',
            provider: 'EuroAir Miles',
            memberId: 'EA-55421',
            tier: 'Silver',
            holderName: 'Demo User',
            memberSince: '2020-08-01',
            points: '18,500 miles',
            expiryDate: '2024-12-31',
            color: '#0EA5E9',
            icon: 'flight',
            notes: 'Priority boarding on intra-EU flights',
            website: 'https://euroair.example.com',
            category: 'Travel',
        },
        {
            id: 'mem-greenmart',
            provider: 'GreenMart Club',
            memberId: 'GM-7745',
            tier: 'Member',
            holderName: 'Demo User',
            memberSince: '2022-02-20',
            points: '€26.50 credit',
            expiryDate: '2024-11-15',
            color: '#22C55E',
            icon: 'shopping_bag',
            notes: '2% cashback on grocery purchases',
            website: 'https://greenmart.example.com',
            category: 'Retail',
        },
    ],
    importExportHistory: [],
    tags: [],
    incomeCategories: MOCK_INCOME_CATEGORIES, // Keep default categories
    expenseCategories: MOCK_EXPENSE_CATEGORIES,
    billsAndPayments: [],
    accountOrder: ['acc-checking', 'acc-savings', 'acc-credit', 'acc-brokerage', 'acc-crypto'],
    taskOrder: [],
    manualWarrantPrices: {},
    priceHistory: {}, // New field for manual price history
    invoices: [],
    userStats: { currentStreak: 0, longestStreak: 0, lastLogDate: '', predictionWins: 0, predictionTotal: 0 },
    predictions: [],
    enableBankingConnections: [],
    preferences: {
        currency: 'EUR (€)',
        language: 'English (en)',
        timezone: typeof Intl !== 'undefined' ? Intl.DateTimeFormat().resolvedOptions().timeZone : 'local',
        dateFormat: 'DD/MM/YYYY',
        defaultPeriod: 'MTD',
        defaultAccountOrder: 'name',
        country: 'Belgium',
        defaultForecastPeriod: '1Y',
        brandfetchClientId: '',
        twelveDataApiKey: '',
        merchantLogoOverrides: {},
    },
};

export const emptyFinancialData: FinancialData = {
    accounts: [],
    transactions: [],
    investmentTransactions: [],
    recurringTransactions: [],
    recurringTransactionOverrides: [],
    loanPaymentOverrides: {},
    financialGoals: [],
    budgets: [],
    tasks: [],
    taskOrder: [],
    warrants: [],
    memberships: [],
    importExportHistory: [],
    incomeCategories: [],
    expenseCategories: [],
    preferences: initialFinancialData.preferences,
    billsAndPayments: [],
    accountOrder: [],
    tags: [],
    manualWarrantPrices: {},
    priceHistory: {},
    invoices: [],
    userStats: { currentStreak: 0, longestStreak: 0, lastLogDate: '', predictionWins: 0, predictionTotal: 0 },
    predictions: [],
    enableBankingConnections: [],
};

export const createDemoUser = (): User => ({
    firstName: 'Demo',
    lastName: 'User',
    email: 'demo@crystal.finance',
    profilePictureUrl: `https://i.pravatar.cc/150?u=demo@crystal.finance`,
    role: 'Member',
    phone: undefined,
    address: undefined,
    is2FAEnabled: false,
    status: 'Active',
    lastLogin: new Date().toISOString(),
});
