import React from 'react';
import * as UntitleduiIcons from '@untitledui/icons';

// Mapping from legacy Material Symbol / Lucide icon names to @untitledui/icons component names
export const ICON_NAME_MAP: Record<string, keyof typeof UntitleduiIcons> = {
  // Navigation & Core UI
  space_dashboard: 'LayoutGrid01',
  dashboard: 'LayoutGrid01',
  command: 'Command',
  command_center: 'Command',
  wallet: 'Wallet01',
  account_balance_wallet: 'Wallet01',
  receipt_long: 'Receipt',
  receipt: 'Receipt',
  analytics: 'TrendUp01',
  show_chart: 'TrendUp01',
  trending_up: 'TrendUp01',
  trending_down: 'TrendDown01',
  bar_chart: 'BarChart01',
  pie_chart: 'PieChart01',
  candlestick_chart: 'LineChartUp01',
  calendar_month: 'Calendar',
  calendar_today: 'Calendar',
  event: 'Calendar',
  schedule: 'Clock',
  loyalty: 'Tag01',
  description: 'File01',
  task_alt: 'CheckSquare',
  emoji_events: 'Trophy01',
  category: 'LayoutGrid01',
  sell: 'Tag01',
  storefront: 'Home01',
  store: 'Home01',
  settings_suggest: 'Settings01',
  settings: 'Settings01',
  api: 'Code01',
  database: 'Server01',
  auto_stories: 'BookOpen01',
  layout_alt: 'LayoutAlt01',
  file_check: 'FileCheck01',
  clock: 'Clock',
  piggy_bank: 'PiggyBank01',
  scale: 'Scale01',
  coins_stacked: 'CoinsStacked01',
  calendar_check: 'CalendarCheck01',
  fast_forward: 'ClockFastForward',
  circle_cut: 'CircleCut',
  rows: 'Rows01',
  bank_note: 'BankNote03',
  sliders: 'Sliders01',
  marker_pin: 'MarkerPin01',
  git_branch: 'GitBranch01',
  hourglass: 'Hourglass01',
  zap: 'Zap',
  receipt_check: 'ReceiptCheck',
  'brush-01': 'Grid01',
  dashboard_customize: 'Grid01',
  add_square: 'PlusSquare',

  // Actions & Controls
  search: 'SearchMd',
  edit: 'Edit02',
  edit_note: 'Edit02',
  edit_square: 'Edit02',
  delete: 'Trash01',
  delete_forever: 'Trash01',
  delete_sweep: 'Trash01',
  add: 'Plus',
  plus: 'Plus',
  close: 'XClose',
  cancel: 'XClose',
  clear: 'XClose',
  refresh: 'RefreshCw01',
  sync: 'RefreshCw01',
  copy: 'Copy01',
  content_copy: 'Copy01',
  repeat: 'Repeat01',
  tune: 'Sliders01',
  filter_alt: 'FilterLines',
  filter_list: 'FilterLines',
  drag_indicator: 'DotsGrid',
  swap_vert: 'SwitchVertical01',
  swap_horiz: 'SwitchHorizontal01',
  sync_alt: 'SwitchHorizontal01',
  more_vert: 'DotsVertical',
  more_horiz: 'DotsHorizontal',
  expand_more: 'ChevronDown',
  expand_less: 'ChevronUp',
  keyboard_double_arrow_up: 'ChevronUp',
  unfold_more: 'ChevronSelectorVertical',

  // Directional
  arrow_back: 'ArrowLeft',
  arrow_left: 'ArrowLeft',
  arrow_forward: 'ArrowRight',
  arrow_right: 'ArrowRight',
  arrow_upward: 'ArrowUp',
  arrow_drop_up: 'ArrowUp',
  arrow_downward: 'ArrowDown',
  arrow_drop_down: 'ArrowDown',
  chevron_left: 'ChevronLeft',
  chevron_right: 'ChevronRight',
  chevron_down: 'ChevronDown',
  chevron_up: 'ChevronUp',
  last_page: 'ChevronLeft',
  first_page: 'ChevronRight',
  subdirectory_arrow_right: 'CornerDownRight',

  // Finance & Banking
  account_balance: 'Bank',
  savings: 'PiggyBank01',
  credit_card: 'CreditCard01',
  request_quote: 'CurrencyDollar',
  real_estate_agent: 'Home01',
  home: 'Home01',
  payments: 'Coins01',
  monetization_on: 'Coins01',
  attach_money: 'CurrencyDollar',
  paid: 'Coins01',
  price_check: 'ReceiptCheck',
  currency_exchange: 'Coins01',
  currency_bitcoin: 'Coins01',
  currency: 'CurrencyDollar',
  euro: 'CurrencyEuro',
  local_atm: 'Bank',
  atm: 'Bank',
  assured_workload: 'Bank',
  card_membership: 'CreditCard01',
  credit_score: 'CreditCard01',
  price_change: 'Coins01',
  money_off: 'Coins01',
  price: 'CurrencyDollar',
  Price: 'CurrencyDollar',
  Intake: 'Coins01',
  Spend: 'CreditCard01',
  Principal: 'Bank',

  // Status & Feedback
  info: 'InfoCircle',
  help: 'HelpCircle',
  help_outline: 'HelpCircle',
  warning: 'AlertTriangle',
  error: 'AlertCircle',
  error_outline: 'AlertCircle',
  dangerous: 'AlertTriangle',
  check: 'Check',
  done: 'Check',
  done_all: 'Check',
  verified: 'CheckCircle',
  check_circle: 'CheckCircle',
  security: 'Shield01',
  shield: 'Shield01',
  safety_check: 'Shield01',
  shield_with_heart: 'Shield01',
  no_crash: 'Shield01',
  verified_user: 'UserCheck01',
  priority_high: 'AlertTriangle',

  // Communications & Auth
  mail: 'Mail01',
  email: 'Mail01',
  contact_mail: 'Mail01',
  lock: 'Lock01',
  password: 'Lock01',
  key: 'Key01',
  login: 'LogIn01',
  logout: 'LogOut01',
  visibility: 'Eye',
  visibility_off: 'EyeOff',
  science: 'Zap',
  insights: 'TrendUp01',
  notes: 'File01',

  // Vehicles, Assets, Housing
  directions_car: 'Truck01',
  commute: 'Train',
  train: 'Train',
  flight: 'Plane',
  flight_takeoff: 'Plane',
  flight_land: 'Plane',
  cottage: 'Home01',
  apartment: 'Home01',
  house: 'Home01',
  hotel: 'Home01',
  deck: 'Home01',
  roofing: 'Home01',
  yard: 'Home01',
  foundation: 'Building01',
  corporate_fare: 'Building01',
  home_work: 'Building01',
  garage: 'Truck01',

  // Shopping, Dining, Lifestyle
  shopping_bag: 'ShoppingBag01',
  shopping_cart: 'ShoppingCart01',
  shopping_basket: 'ShoppingBag01',
  local_mall: 'ShoppingBag01',
  local_offer: 'Tag01',
  restaurant: 'ShoppingBag01',
  restaurant_menu: 'ShoppingBag01',
  local_cafe: 'ShoppingBag01',
  coffee: 'ShoppingBag01',
  local_bar: 'ShoppingBag01',
  emoji_food_beverage: 'ShoppingBag01',
  liquor: 'ShoppingBag01',
  local_pizza: 'ShoppingBag01',
  fastfood: 'ShoppingBag01',
  delivery_dining: 'Truck01',
  local_fire_department: 'Zap',
  swords: 'Shield01',

  // Media, Tech, Devices
  devices: 'Monitor01',
  smartphone: 'Phone01',
  phone: 'Phone01',
  stay_current_portrait: 'Phone01',
  laptop: 'Laptop01',
  desktop_windows: 'Monitor01',
  tablet: 'Tablet01',
  tv: 'Tv01',
  router: 'Wifi',
  cloud: 'Cloud01',
  cloud_download: 'DownloadCloud01',
  cloud_upload: 'UploadCloud01',
  download: 'Download01',
  upload: 'Upload01',
  upload_file: 'Upload01',
  camera_alt: 'Camera01',
  photo_camera: 'Camera01',
  image: 'Image01',
  music_note: 'MusicNote01',
  mic: 'Microphone01',
  chat: 'MessageSquare01',

  // Charts & Analytics
  donut_large: 'PieChart01',
  stacked_line_chart: 'LineChartUp01',
  multiline_chart: 'LineChartUp01',
  waterfall_chart: 'BarChart01',
  monitoring: 'Activity',
  query_stats: 'SearchMd',
  timeline: 'TrendUp01',
  flowsheet: 'GitBranch01',
  schema: 'GitBranch01',
  database_search: 'Server01',
  storage: 'Server01',

  // Miscellaneous & Specialized UI
  work: 'Briefcase01',
  badge: 'Passcode',
  construction: 'Tool01',
  build: 'Tool01',
  fingerprint: 'Fingerprint01',
  map: 'Map01',
  location_on: 'MarkerPin01',
  electric_car: 'Truck01',
  local_gas_station: 'Zap',
  directions_bus: 'Truck01',
  weekend: 'Home01',
  chair: 'Home01',
  living: 'Home01',
  event_seat: 'Home01',
  bed: 'Home01',
  night_shelter: 'Home01',
  crib: 'Home01',
  baby_changing_station: 'User01',
  family_restroom: 'Users01',
  child_care: 'User01',
  pets: 'Heart',
  bathtub: 'Home01',
  local_florist: 'Sun',
  park: 'Sun',
  nature: 'Sun',
  forest: 'Sun',
  memory: 'CpuChip01',
  code: 'Code01',
  terminal: 'Terminal',
  photo_library: 'Image01',
  collections: 'Image01',
  videocam: 'VideoRecorder',
  notifications: 'Bell01',
  notifications_active: 'Bell01',
  language: 'Globe01',
  translate: 'Translate01',
  travel_explore: 'Globe01',
  public: 'Globe01',
  public_off: 'Globe01',
  alarm: 'AlarmClock',
  timer: 'Hourglass01',
  history: 'ClockRewind',
  history_toggle_off: 'ClockRewind',
  undo: 'ArrowLeft',
  restore: 'RefreshCw01',
  settings_backup_restore: 'RefreshCw01',
  published_with_changes: 'RefreshCw01',
  update: 'RefreshCw01',
  watch_later: 'Clock',
  pending_actions: 'Clock',
  health_and_safety: 'Shield01',
  monitor_heart: 'Activity',
  healing: 'MedicalCross',
  medication: 'MedicalCircle',
  medical_services: 'MedicalCross',
  volunteer_activism: 'Heart',
  self_improvement: 'Sun',
  fitness_center: 'Activity',
  speed: 'Activity',
  sports_esports: 'GamingPad01',
  toys: 'GamingPad01',
  sports_tennis: 'Activity',
  sports_soccer: 'Activity',
  sports_basketball: 'Activity',
  run_circle: 'Activity',
  hiking: 'User01',
  pool: 'Sun',
  cake: 'Gift01',
  lightbulb: 'Lightbulb01',
  emoji_objects: 'Lightbulb01',
  electric_bolt: 'Zap',
  bolt: 'Zap',
  psychic: 'Zap',
  psychology: 'Zap',
  psychology_alt: 'Zap',
  rocket_launch: 'Zap',
  auto_awesome: 'Stars01',
  stars: 'Star01',
  battery_charging_full: 'BatteryCharging01',
  solar_power: 'Sun',
  eco: 'Sun',
  water_drop: 'Drop',
  wb_sunny: 'Sun',
  dark_mode: 'Moon01',
  light_mode: 'Sun',
  search_off: 'SearchMd',
  search_activity: 'SearchMd',
  apps: 'LayoutGrid01',
  grid_view: 'LayoutGrid01',
  table_view: 'Table',
  table_chart: 'Table',
  table_rows: 'Rows01',
  view_list: 'List',
  view_kanban: 'LayoutGrid01',
  view_timeline: 'BarChart01',
  view_week: 'Calendar',
  view_agenda: 'Rows01',
  view_headline: 'Rows01',
  splitscreen: 'Columns01',
  vertical_split: 'Columns01',
  density_medium: 'Rows01',
  inbox: 'Inbox01',
  inbox_customize: 'Inbox01',
  transform: 'RefreshCw01',
  edit_calendar: 'Calendar',
  event_available: 'CalendarCheck01',
  event_busy: 'Calendar',
  event_repeat: 'CalendarPlus01',
  event_upcoming: 'Calendar',
  today: 'Calendar',
  content_paste: 'Clipboard',
  assignment_return: 'ArrowLeft',
  card_giftcard: 'Gift01',
  house_repair_service: 'Tool01',
  home_repair_service: 'Tool01',
  car_crash: 'AlertTriangle',
  car_repair: 'Tool01',
  local_taxi: 'Truck01',
  local_parking: 'MarkerPin01',
  local_police: 'Shield01',
  checkroom: 'ShoppingBag01',
  face: 'FaceSmile',
  cleaning_services: 'Tool01',
  theaters: 'Film01',
  confirmation_number: 'Ticket01',
  stroller: 'User01',
  face_3: 'User01',
  vaccines: 'MedicalCircle',
  cast_for_education: 'Monitor01',
  menu_book: 'BookOpen01',
  history_edu: 'BookOpen01',
  school: 'GraduationHat01',
  tour: 'Compass01',
  explore: 'Compass01',
  radar: 'Target01',
  target: 'Target01',
  track_changes: 'Target01',
  center_focus_strong: 'Target01',
  sentiment_very_dissatisfied: 'AlertCircle',
  sentiment_dissatisfied: 'AlertCircle',
  extension: 'PuzzlePiece01',
  policy: 'FileCheck01',
  contract: 'FileCheck01',
  rule: 'FileCheck01',
  fact_check: 'FileCheck01',
  diamond: 'Star01',
  handshake: 'Users01',
  groups: 'Users01',
  account_circle: 'UserCircle',
  person: 'User01',
  person_add: 'UserPlus01',
  account_tree: 'Share01',
  engineering: 'Tool01',
  checklist_rtl: 'CheckSquare',
  circle: 'Circle',
  stop_circle: 'XCircle',
  colorize: 'Palette',
  palette: 'Palette',
  style: 'Palette',
  flag: 'Flag01',
  folder: 'Folder',
  folder_shared: 'Folder',
  format_list_numbered: 'List',
  list_alt: 'List',
  list_alt_off: 'List',
  gavel: 'Scale01',
  inventory_2: 'Archive',
  label: 'Tag01',
  label_important: 'Tag01',
  label_off: 'Tag01',
  tag: 'Tag01',
  layers: 'LayersThree01',
  pattern: 'LayersThree01',
  subscriptions: 'LayersThree01',
  link: 'Link01',
  link_off: 'Link01',
  military_tech: 'Award01',
  workspace_premium: 'Award01',
  podium: 'Trophy01',
  open_in_new: 'LinkExternal01',
  remove: 'Minus',
  save: 'Save01',
  send: 'Send01',
  send_and_archive: 'Send01',
  settings_ethernet: 'Settings01',
  settings_input_component: 'Settings01',

  // Newly Audited Icons
  ad_group: 'LayoutGrid01',
  add_a_photo: 'Camera01',
  add_circle: 'PlusCircle',
  add_link: 'Link01',
  add_moderator: 'Shield01',
  address: 'MarkerPin01',
  ads_click: 'CursorClick01',
  alternate_email: 'AtSign',
  architecture: 'Building01',
  archive: 'Archive',
  arrow_circle_down: 'ArrowCircleDown',
  arrow_circle_up: 'ArrowCircleUp',
  assessment: 'BarChart01',
  assignment: 'Clipboard',
  auto_fix: 'Zap',
  autorenew: 'RefreshCw01',
  backup: 'UploadCloud01',
  balance: 'Scale01',
  Balance: 'Scale01',
  bar_chart_4_bars: 'BarChart01',
  block: 'XCircle',
  bookmark: 'Bookmark',
  brand_awareness: 'Target01',
  compare_arrows: 'SwitchHorizontal01',
  menu: 'Menu01',
  movie: 'Film01',
  smart_toy: 'CpuChip01',
  'smart-fetcher-price': 'Zap',
  thumb_down: 'ThumbsDown',
  thumb_up: 'ThumbsUp',
};

export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name?: string;
  className?: string;
  size?: number | string;
  strokeWidth?: number | string;
  color?: string;
  title?: string;
  style?: React.CSSProperties;
}

export const Icon: React.FC<IconProps> = ({
  name,
  className = '',
  size,
  strokeWidth = 2,
  color = 'currentColor',
  style,
  ...props
}) => {
  if (!name) return null;

  // Resolve component name from map or direct match
  const cleanName = name.trim();
  const pascalName = cleanName.replace(/(^[a-z]|[_\-\s]+([a-z0-9]))/gi, (_, p1, p2) => (p2 || p1).toUpperCase());
  const componentName =
    ICON_NAME_MAP[cleanName] ||
    ICON_NAME_MAP[cleanName.toLowerCase()] ||
    (cleanName in UntitleduiIcons ? (cleanName as keyof typeof UntitleduiIcons) : null) ||
    (pascalName in UntitleduiIcons ? (pascalName as keyof typeof UntitleduiIcons) : null);

  const IconComponent = componentName
    ? (UntitleduiIcons[componentName] as React.ComponentType<any>)
    : UntitleduiIcons.Grid01;

  // Standardize sizing: If no explicit width/height in className or size prop, default to inline text scaling (1em x 1em)
  const hasWidthClass = /\b(w-\d+|w-\[.*\]|w-full|w-screen|w-auto)\b/.test(className);
  const hasHeightClass = /\b(h-\d+|h-\[.*\]|h-full|h-screen|h-auto)\b/.test(className);

  const defaultSizeClass = !hasWidthClass && !hasHeightClass && !size ? 'w-[1em] h-[1em] inline-block shrink-0 align-middle' : '';

  return (
    <IconComponent
      className={`${defaultSizeClass} ${className}`.trim()}
      size={size}
      strokeWidth={strokeWidth}
      color={color}
      style={style}
      {...props}
    />
  );
};

export default Icon;
