import React from 'react';
import {
  IconProps as PhosphorIconProps,
  House,
  HouseLine,
  SquaresFour,
  MagnifyingGlass,
  Sliders,
  Faders,
  FadersHorizontal,
  Funnel,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  CaretDown,
  CaretUp,
  CaretLeft,
  CaretRight,
  CaretUpDown,
  CaretDoubleUp,
  CaretDoubleLeft,
  CaretDoubleRight,
  ArrowElbowDownRight,
  ArrowSquareOut,
  ArrowCounterClockwise,
  DotsThreeVertical,
  DotsThree,
  DotsSixVertical,
  Plus,
  PlusCircle,
  PlusSquare,
  Minus,
  X,
  XCircle,
  XSquare,
  Check,
  CheckCircle,
  Checks,
  Copy,
  PencilSimple,
  Trash,
  Repeat,
  ArrowsDownUp,
  ArrowsLeftRight,
  User,
  UserCircle,
  UserPlus,
  Users,
  UsersThree,
  UserCheck,
  Handshake,
  Trophy,
  Medal,
  Crown,
  Shield,
  ShieldCheck,
  Lock,
  LockOpen,
  Key,
  Fingerprint,
  Eye,
  EyeSlash,
  SignIn,
  SignOut,
  Envelope,
  EnvelopeOpen,
  ChatCircle,
  ChatDots,
  Bell,
  BellRinging,
  Megaphone,
  PaperPlaneRight,
  ShareNetwork,
  At,
  Monitor,
  Laptop,
  DeviceMobile,
  DeviceTablet,
  Television,
  WifiHigh,
  Camera,
  Image,
  MusicNotes,
  Microphone,
  Play,
  Pause,
  PauseCircle,
  PlayCircle,
  FilmStrip,
  Columns,
  Rows,
  Table,
  Stack,
  Palette,
  Cursor,
  MagicWand,
  Sparkle,
  Crop,
  File,
  FileText,
  FileDoc,
  FilePlus,
  Folder,
  FolderOpen,
  Archive,
  ClipboardText,
  Cloud,
  CloudCheck,
  CloudArrowUp,
  CloudArrowDown,
  DownloadSimple,
  UploadSimple,
  FloppyDisk,
  BookOpen,
  Clock,
  ClockClockwise,
  ClockCounterClockwise,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  Hourglass,
  Alarm,
  Timer,
  MapPin,
  MapTrifold,
  Compass,
  Globe,
  Translate,
  Airplane,
  AirplaneTakeoff,
  AirplaneLanding,
  Car,
  CarSimple,
  Train,
  Buildings,
  Ticket,
  Heart,
  Heartbeat,
  FirstAidKit,
  Pill,
  Barbell,
  Footprints,
  ShoppingBag,
  ShoppingCart,
  ForkKnife,
  Coffee,
  BeerBottle,
  Pizza,
  Gift,
  GameController,
  Armchair,
  Bed,
  Code,
  Terminal,
  Cpu,
  Database,
  GitBranch,
  GitCommit,
  GitMerge,
  GitFork,
  Bug,
  PuzzlePiece,
  Wrench,
  Certificate,
  SoccerBall,
  Basketball,
  TennisBall,
  Sun,
  Moon,
  CloudSun,
  CloudRain,
  Drop,
  Lightning,
  Plant,
  Tree,
  Gear,
  GearSix,
  Info,
  Question,
  Warning,
  WarningCircle,
  WarningOctagon,
  Smiley,
  Star,
  BookmarkSimple,
  Flag,
  Package,
  Link,
  LinkBreak,
  CheckSquare,
  List,
  ListNumbers,
  Command,
  Bank,
  Wallet,
  CreditCard,
  Coins,
  PiggyBank,
  Receipt,
  CurrencyDollar,
  CurrencyEur,
  CurrencyGbp,
  CurrencyBtc,
  CurrencyEth,
  Money,
  HandCoins,
  Scales,
  Vault,
  Tag,
  Invoice,
  TrendUp,
  TrendDown,
  ChartBar,
  ChartPie,
  ChartLine,
  ChartLineUp,
  ChartLineDown,
  ChartScatter,
  ChartDonut,
  Pulse,
  Target,
  Gauge,
  FastForward,
  CircleHalf,
  Circle,
  ThumbsUp,
  ThumbsDown,
  Flask,
  ArrowCircleDown,
  ArrowCircleUp,
  Bathtub,
  Shapes,
} from '@phosphor-icons/react';

// Explicit components map for tree-shaking & fast lookup
const ICONS: Record<string, React.ComponentType<any>> = {
  House,
  HouseLine,
  SquaresFour,
  MagnifyingGlass,
  Sliders,
  Faders,
  FadersHorizontal,
  Funnel,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  CaretDown,
  CaretUp,
  CaretLeft,
  CaretRight,
  CaretUpDown,
  CaretDoubleUp,
  CaretDoubleLeft,
  CaretDoubleRight,
  ArrowElbowDownRight,
  ArrowSquareOut,
  ArrowCounterClockwise,
  DotsThreeVertical,
  DotsThree,
  DotsSixVertical,
  Plus,
  PlusCircle,
  PlusSquare,
  Minus,
  X,
  XCircle,
  XSquare,
  Check,
  CheckCircle,
  Checks,
  Copy,
  PencilSimple,
  Trash,
  Repeat,
  ArrowsDownUp,
  ArrowsLeftRight,
  User,
  UserCircle,
  UserPlus,
  Users,
  UsersThree,
  UserCheck,
  Handshake,
  Trophy,
  Medal,
  Crown,
  Shield,
  ShieldCheck,
  Lock,
  LockOpen,
  Key,
  Fingerprint,
  Eye,
  EyeSlash,
  SignIn,
  SignOut,
  Envelope,
  EnvelopeOpen,
  ChatCircle,
  ChatDots,
  Bell,
  BellRinging,
  Megaphone,
  PaperPlaneRight,
  ShareNetwork,
  At,
  Monitor,
  Laptop,
  DeviceMobile,
  DeviceTablet,
  Television,
  WifiHigh,
  Camera,
  Image,
  MusicNotes,
  Microphone,
  Play,
  Pause,
  PauseCircle,
  PlayCircle,
  FilmStrip,
  Columns,
  Rows,
  Table,
  Stack,
  Palette,
  Cursor,
  MagicWand,
  Sparkle,
  Crop,
  File,
  FileText,
  FileDoc,
  FilePlus,
  Folder,
  FolderOpen,
  Archive,
  ClipboardText,
  Cloud,
  CloudCheck,
  CloudArrowUp,
  CloudArrowDown,
  DownloadSimple,
  UploadSimple,
  FloppyDisk,
  BookOpen,
  Clock,
  ClockClockwise,
  ClockCounterClockwise,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  Hourglass,
  Alarm,
  Timer,
  MapPin,
  MapTrifold,
  Compass,
  Globe,
  Translate,
  Airplane,
  AirplaneTakeoff,
  AirplaneLanding,
  Car,
  CarSimple,
  Train,
  Buildings,
  Ticket,
  Heart,
  Heartbeat,
  FirstAidKit,
  Pill,
  Barbell,
  Footprints,
  ShoppingBag,
  ShoppingCart,
  ForkKnife,
  Coffee,
  BeerBottle,
  Pizza,
  Gift,
  GameController,
  Armchair,
  Bed,
  Code,
  Terminal,
  Cpu,
  Database,
  GitBranch,
  GitCommit,
  GitMerge,
  GitFork,
  Bug,
  PuzzlePiece,
  Wrench,
  Certificate,
  SoccerBall,
  Basketball,
  TennisBall,
  Sun,
  Moon,
  CloudSun,
  CloudRain,
  Drop,
  Lightning,
  Plant,
  Tree,
  Gear,
  GearSix,
  Info,
  Question,
  Warning,
  WarningCircle,
  WarningOctagon,
  Smiley,
  Star,
  BookmarkSimple,
  Flag,
  Package,
  Link,
  LinkBreak,
  CheckSquare,
  List,
  ListNumbers,
  Command,
  Bank,
  Wallet,
  CreditCard,
  Coins,
  PiggyBank,
  Receipt,
  CurrencyDollar,
  CurrencyEur,
  CurrencyGbp,
  CurrencyBtc,
  CurrencyEth,
  Money,
  HandCoins,
  Scales,
  Vault,
  Tag,
  Invoice,
  TrendUp,
  TrendDown,
  ChartBar,
  ChartPie,
  ChartLine,
  ChartLineUp,
  ChartLineDown,
  ChartScatter,
  ChartDonut,
  Pulse,
  Activity: Pulse,
  Target,
  Gauge,
  FastForward,
  CircleHalf,
  Circle,
  ThumbsUp,
  ThumbsDown,
  Flask,
  ArrowCircleDown,
  ArrowCircleUp,
  Bathtub,
  Shapes,
};

// Mapping from legacy Material Symbol / Lucide / UntitledUI icon names to Phosphor component keys
export const ICON_NAME_MAP: Record<string, string> = {
  // Navigation & Core UI
  space_dashboard: 'SquaresFour',
  dashboard: 'SquaresFour',
  command: 'Command',
  command_center: 'Command',
  wallet: 'Wallet',
  account_balance_wallet: 'Wallet',
  receipt_long: 'Receipt',
  receipt: 'Receipt',
  analytics: 'TrendUp',
  show_chart: 'TrendUp',
  trending_up: 'TrendUp',
  trending_down: 'TrendDown',
  bar_chart: 'ChartBar',
  pie_chart: 'ChartPie',
  candlestick_chart: 'ChartLineUp',
  calendar_month: 'Calendar',
  calendar_today: 'Calendar',
  event: 'Calendar',
  schedule: 'Clock',
  loyalty: 'Tag',
  description: 'FileText',
  task_alt: 'CheckSquare',
  emoji_events: 'Trophy',
  category: 'SquaresFour',
  sell: 'Tag',
  storefront: 'House',
  store: 'House',
  settings_suggest: 'Gear',
  settings: 'Gear',
  api: 'Code',
  database: 'Database',
  auto_stories: 'BookOpen',
  layout_alt: 'Columns',
  file_check: 'FileDoc',
  clock: 'Clock',
  piggy_bank: 'PiggyBank',
  scale: 'Scales',
  coins_stacked: 'Coins',
  calendar_check: 'CalendarCheck',
  fast_forward: 'FastForward',
  circle_cut: 'CircleHalf',
  rows: 'Rows',
  bank_note: 'Money',
  sliders: 'Sliders',
  marker_pin: 'MapPin',
  git_branch: 'GitBranch',
  hourglass: 'Hourglass',
  zap: 'Lightning',
  receipt_check: 'Receipt',
  'brush-01': 'Palette',
  dashboard_customize: 'SquaresFour',
  add_square: 'PlusSquare',

  // Actions & Controls
  search: 'MagnifyingGlass',
  edit: 'PencilSimple',
  edit_note: 'PencilSimple',
  edit_square: 'PencilSimple',
  delete: 'Trash',
  delete_forever: 'Trash',
  delete_sweep: 'Trash',
  add: 'Plus',
  plus: 'Plus',
  close: 'X',
  cancel: 'X',
  clear: 'X',
  refresh: 'ArrowCounterClockwise',
  sync: 'ArrowCounterClockwise',
  copy: 'Copy',
  content_copy: 'Copy',
  repeat: 'Repeat',
  tune: 'Sliders',
  filter_alt: 'Funnel',
  filter_list: 'Funnel',
  drag_indicator: 'DotsSixVertical',
  swap_vert: 'ArrowsDownUp',
  swap_horiz: 'ArrowsLeftRight',
  sync_alt: 'ArrowsLeftRight',
  more_vert: 'DotsThreeVertical',
  more_horiz: 'DotsThree',
  expand_more: 'CaretDown',
  expand_less: 'CaretUp',
  keyboard_double_arrow_up: 'CaretDoubleUp',
  unfold_more: 'CaretUpDown',

  // Directional
  arrow_back: 'ArrowLeft',
  arrow_left: 'ArrowLeft',
  arrow_forward: 'ArrowRight',
  arrow_right: 'ArrowRight',
  arrow_upward: 'ArrowUp',
  arrow_drop_up: 'CaretUp',
  arrow_downward: 'ArrowDown',
  arrow_drop_down: 'CaretDown',
  chevron_left: 'CaretLeft',
  chevron_right: 'CaretRight',
  chevron_down: 'CaretDown',
  chevron_up: 'CaretUp',
  last_page: 'CaretDoubleRight',
  first_page: 'CaretDoubleLeft',
  subdirectory_arrow_right: 'ArrowElbowDownRight',

  // Finance & Banking
  account_balance: 'Bank',
  savings: 'PiggyBank',
  credit_card: 'CreditCard',
  request_quote: 'CurrencyDollar',
  real_estate_agent: 'House',
  home: 'House',
  payments: 'Coins',
  monetization_on: 'Coins',
  attach_money: 'CurrencyDollar',
  paid: 'Coins',
  price_check: 'Receipt',
  currency_exchange: 'CurrencyDollar',
  currency_bitcoin: 'CurrencyBtc',
  currency: 'CurrencyDollar',
  euro: 'CurrencyEur',
  local_atm: 'Bank',
  atm: 'Bank',
  assured_workload: 'Bank',
  card_membership: 'CreditCard',
  credit_score: 'CreditCard',
  price_change: 'Coins',
  money_off: 'Coins',
  price: 'CurrencyDollar',
  Price: 'CurrencyDollar',
  Intake: 'Coins',
  Spend: 'CreditCard',
  Principal: 'Bank',

  // Status & Feedback
  info: 'Info',
  help: 'Question',
  help_outline: 'Question',
  warning: 'Warning',
  error: 'WarningCircle',
  error_outline: 'WarningCircle',
  dangerous: 'WarningOctagon',
  check: 'Check',
  done: 'Check',
  done_all: 'Checks',
  verified: 'CheckCircle',
  check_circle: 'CheckCircle',
  security: 'Shield',
  shield: 'Shield',
  safety_check: 'ShieldCheck',
  shield_with_heart: 'ShieldCheck',
  no_crash: 'ShieldCheck',
  verified_user: 'UserCheck',
  priority_high: 'Warning',

  // Communications & Auth
  mail: 'Envelope',
  email: 'Envelope',
  contact_mail: 'Envelope',
  lock: 'Lock',
  password: 'Lock',
  key: 'Key',
  login: 'SignIn',
  logout: 'SignOut',
  visibility: 'Eye',
  visibility_off: 'EyeSlash',
  science: 'Flask',
  insights: 'TrendUp',
  notes: 'FileText',

  // Vehicles, Assets, Housing
  directions_car: 'Car',
  commute: 'Train',
  train: 'Train',
  flight: 'Airplane',
  flight_takeoff: 'AirplaneTakeoff',
  flight_land: 'AirplaneLanding',
  cottage: 'House',
  apartment: 'Buildings',
  house: 'House',
  hotel: 'Buildings',
  deck: 'House',
  roofing: 'House',
  yard: 'Plant',
  foundation: 'Buildings',
  corporate_fare: 'Buildings',
  home_work: 'Buildings',
  garage: 'Car',

  // Shopping, Dining, Lifestyle
  shopping_bag: 'ShoppingBag',
  shopping_cart: 'ShoppingCart',
  shopping_basket: 'ShoppingBag',
  local_mall: 'ShoppingBag',
  local_offer: 'Tag',
  restaurant: 'ForkKnife',
  restaurant_menu: 'ForkKnife',
  local_cafe: 'Coffee',
  coffee: 'Coffee',
  local_bar: 'BeerBottle',
  emoji_food_beverage: 'Coffee',
  liquor: 'BeerBottle',
  local_pizza: 'Pizza',
  fastfood: 'Pizza',
  delivery_dining: 'Car',
  local_fire_department: 'Lightning',
  swords: 'Shield',

  // Media, Tech, Devices
  devices: 'Monitor',
  smartphone: 'DeviceMobile',
  phone: 'DeviceMobile',
  stay_current_portrait: 'DeviceMobile',
  laptop: 'Laptop',
  desktop_windows: 'Monitor',
  tablet: 'DeviceTablet',
  tv: 'Television',
  router: 'WifiHigh',
  cloud: 'Cloud',
  cloud_download: 'CloudArrowDown',
  cloud_upload: 'CloudArrowUp',
  download: 'DownloadSimple',
  upload: 'UploadSimple',
  upload_file: 'UploadSimple',
  camera_alt: 'Camera',
  photo_camera: 'Camera',
  image: 'Image',
  music_note: 'MusicNotes',
  mic: 'Microphone',
  chat: 'ChatCircle',

  // Charts & Analytics
  donut_large: 'ChartDonut',
  stacked_line_chart: 'ChartLineUp',
  multiline_chart: 'ChartLineUp',
  waterfall_chart: 'ChartBar',
  monitoring: 'Pulse',
  query_stats: 'MagnifyingGlass',
  timeline: 'TrendUp',
  flowsheet: 'GitBranch',
  schema: 'GitBranch',
  database_search: 'Database',
  storage: 'Database',

  // Miscellaneous & Specialized UI
  work: 'Briefcase',
  badge: 'Medal',
  construction: 'Wrench',
  build: 'Wrench',
  fingerprint: 'Fingerprint',
  map: 'MapTrifold',
  location_on: 'MapPin',
  electric_car: 'Car',
  local_gas_station: 'Lightning',
  directions_bus: 'Car',
  weekend: 'Armchair',
  chair: 'Armchair',
  living: 'Armchair',
  event_seat: 'Armchair',
  bed: 'Bed',
  night_shelter: 'House',
  crib: 'Heart',
  baby_changing_station: 'User',
  family_restroom: 'Users',
  child_care: 'User',
  pets: 'Heart',
  bathtub: 'Bathtub',
  local_florist: 'Plant',
  park: 'Tree',
  nature: 'Tree',
  forest: 'Tree',
  memory: 'Cpu',
  code: 'Code',
  terminal: 'Terminal',
  photo_library: 'Image',
  collections: 'Image',
  videocam: 'VideoCamera',
  notifications: 'Bell',
  notifications_active: 'BellRinging',
  language: 'Globe',
  translate: 'Translate',
  travel_explore: 'Globe',
  public: 'Globe',
  public_off: 'Globe',
  alarm: 'Alarm',
  timer: 'Timer',
  history: 'ClockClockwise',
  history_toggle_off: 'ClockCounterClockwise',
  undo: 'ArrowCounterClockwise',
  restore: 'ArrowCounterClockwise',
  settings_backup_restore: 'ArrowCounterClockwise',
  published_with_changes: 'CheckCircle',
  update: 'ArrowCounterClockwise',
  watch_later: 'Clock',
  pending_actions: 'Clock',
  health_and_safety: 'ShieldCheck',
  monitor_heart: 'Heartbeat',
  healing: 'FirstAidKit',
  medication: 'Pill',
  medical_services: 'FirstAidKit',
  volunteer_activism: 'Heart',
  self_improvement: 'Sun',
  fitness_center: 'Barbell',
  speed: 'Gauge',
  sports_esports: 'GameController',
  toys: 'GameController',
  sports_tennis: 'TennisBall',
  sports_soccer: 'SoccerBall',
  sports_basketball: 'Basketball',
  run_circle: 'Footprints',
  hiking: 'Footprints',
  pool: 'Sun',
  cake: 'Gift',
  lightbulb: 'Lightbulb',
  emoji_objects: 'Lightbulb',
  electric_bolt: 'Lightning',
  bolt: 'Lightning',
  psychic: 'Lightning',
  psychology: 'Sparkle',
  psychology_alt: 'Sparkle',
  rocket_launch: 'Lightning',
  auto_awesome: 'Sparkle',
  stars: 'Star',
  battery_charging_full: 'BatteryCharging',
  solar_power: 'Sun',
  eco: 'Plant',
  water_drop: 'Drop',
  wb_sunny: 'Sun',
  dark_mode: 'Moon',
  light_mode: 'Sun',
  search_off: 'MagnifyingGlass',
  search_activity: 'MagnifyingGlass',
  apps: 'SquaresFour',
  grid_view: 'SquaresFour',
  table_view: 'Table',
  table_chart: 'Table',
  table_rows: 'Rows',
  view_list: 'List',
  view_kanban: 'SquaresFour',
  view_timeline: 'ChartBar',
  view_week: 'Calendar',
  view_agenda: 'Rows',
  view_headline: 'Rows',
  splitscreen: 'Columns',
  vertical_split: 'Columns',
  density_medium: 'Rows',
  inbox: 'Envelope',
  inbox_customize: 'Envelope',
  transform: 'ArrowCounterClockwise',
  edit_calendar: 'Calendar',
  event_available: 'CalendarCheck',
  event_busy: 'Calendar',
  event_repeat: 'CalendarPlus',
  event_upcoming: 'Calendar',
  today: 'Calendar',
  content_paste: 'ClipboardText',
  assignment_return: 'ArrowLeft',
  card_giftcard: 'Gift',
  house_repair_service: 'Wrench',
  home_repair_service: 'Wrench',
  car_crash: 'Warning',
  car_repair: 'Wrench',
  local_taxi: 'Car',
  local_parking: 'MapPin',
  local_police: 'Shield',
  checkroom: 'ShoppingBag',
  face: 'Smiley',
  cleaning_services: 'Wrench',
  theaters: 'FilmStrip',
  confirmation_number: 'Ticket',
  stroller: 'User',
  face_3: 'User',
  vaccines: 'Pill',
  cast_for_education: 'Monitor',
  menu_book: 'BookOpen',
  history_edu: 'BookOpen',
  school: 'GraduationCap',
  tour: 'Compass',
  explore: 'Compass',
  radar: 'Target',
  target: 'Target',
  track_changes: 'Target',
  center_focus_strong: 'Target',
  sentiment_very_dissatisfied: 'WarningCircle',
  sentiment_dissatisfied: 'WarningCircle',
  extension: 'PuzzlePiece',
  policy: 'FileDoc',
  contract: 'FileDoc',
  rule: 'FileDoc',
  fact_check: 'FileDoc',
  diamond: 'Star',
  handshake: 'Handshake',
  groups: 'Users',
  account_circle: 'UserCircle',
  person: 'User',
  person_add: 'UserPlus',
  account_tree: 'ShareNetwork',
  engineering: 'Wrench',
  checklist_rtl: 'CheckSquare',
  circle: 'Circle',
  stop_circle: 'XCircle',
  colorize: 'Palette',
  palette: 'Palette',
  style: 'Palette',
  flag: 'Flag',
  folder: 'Folder',
  folder_shared: 'Folder',
  format_list_numbered: 'ListNumbers',
  list_alt: 'List',
  list_alt_off: 'List',
  gavel: 'Scales',
  inventory_2: 'Archive',
  label: 'Tag',
  label_important: 'Tag',
  label_off: 'Tag',
  tag: 'Tag',
  layers: 'Stack',
  pattern: 'Stack',
  subscriptions: 'Stack',
  link: 'Link',
  link_off: 'LinkBreak',
  military_tech: 'Medal',
  workspace_premium: 'Medal',
  podium: 'Trophy',
  open_in_new: 'ArrowSquareOut',
  remove: 'Minus',
  save: 'FloppyDisk',
  send: 'PaperPlaneRight',
  send_and_archive: 'PaperPlaneRight',
  settings_ethernet: 'Gear',
  settings_input_component: 'Gear',

  // Newly Audited Icons
  'cryptocurrency-01': 'CurrencyBtc',
  'link-04': 'Link',
  Building02: 'Buildings',
  'marker-pin-04': 'MapPin',
  line_chart_up: 'ChartLineUp',
  hourglass_top: 'Hourglass',
  elderly: 'User',
  PresentationChart01: 'ChartBar',
  call_split: 'GitFork',
  auto_fix_high: 'Sparkle',
  date_range: 'Calendar',
  CheckVerified01: 'CheckCircle',
  low_priority: 'Flag',
  radio_button_unchecked: 'Circle',
  timelapse: 'Timer',
  FileText01: 'FileText',
  Activity: 'Pulse',
  cloud_done: 'CloudCheck',
  Box: 'Package',
  Search01: 'MagnifyingGlass',
  award: 'Medal',
  Certificate01: 'Certificate',
  call_merge: 'GitMerge',
  location_off: 'MapPinLine',
  merge_type: 'GitMerge',
  ad_group: 'SquaresFour',
  add_a_photo: 'Camera',
  add_circle: 'PlusCircle',
  add_link: 'Link',
  add_moderator: 'Shield',
  address: 'MapPin',
  ads_click: 'Cursor',
  alternate_email: 'At',
  architecture: 'Buildings',
  archive: 'Archive',
  arrow_circle_down: 'ArrowCircleDown',
  arrow_circle_up: 'ArrowCircleUp',
  assessment: 'ChartBar',
  assignment: 'ClipboardText',
  auto_fix: 'Sparkle',
  autorenew: 'ArrowCounterClockwise',
  backup: 'CloudArrowUp',
  balance: 'Scales',
  Balance: 'Scales',
  bar_chart_4_bars: 'ChartBar',
  block: 'XCircle',
  bookmark: 'BookmarkSimple',
  brand_awareness: 'Target',
  compare_arrows: 'ArrowsLeftRight',
  menu: 'List',
  movie: 'FilmStrip',
  smart_toy: 'Cpu',
  'smart-fetcher-price': 'Lightning',
  thumb_down: 'ThumbsDown',
  thumb_up: 'ThumbsUp',
  magic_wand: 'MagicWand',
  sparkles: 'Sparkle',
  bank: 'Bank',
  institution: 'Bank',
  aggr_volume: 'Coins',
  alert_triangle: 'Warning',
  code_snippet: 'Code',
  eye: 'Eye',
  eye_off: 'EyeSlash',

  // UntitledUI backward mappings
  LayoutGrid01: 'SquaresFour',
  LayoutAlt01: 'Columns',
  Wallet01: 'Wallet',
  ReceiptCheck: 'Receipt',
  TrendUp01: 'TrendUp',
  TrendDown01: 'TrendDown',
  BarChart01: 'ChartBar',
  PieChart01: 'ChartPie',
  LineChartUp01: 'ChartLineUp',
  Tag01: 'Tag',
  File01: 'FileText',
  Trophy01: 'Trophy',
  Home01: 'House',
  Settings01: 'Gear',
  Code01: 'Code',
  Code02: 'Code',
  Server01: 'Database',
  BookOpen01: 'BookOpen',
  PiggyBank01: 'PiggyBank',
  Scale01: 'Scales',
  CoinsStacked01: 'Coins',
  Coins01: 'Coins',
  CalendarCheck01: 'CalendarCheck',
  CalendarPlus01: 'CalendarPlus',
  ClockFastForward: 'FastForward',
  Rows01: 'Rows',
  BankNote03: 'Money',
  Sliders01: 'Sliders',
  MarkerPin01: 'MapPin',
  GitBranch01: 'GitBranch',
  Hourglass01: 'Hourglass',
  Grid01: 'SquaresFour',
  SearchMd: 'MagnifyingGlass',
  Edit01: 'PencilSimple',
  Edit02: 'PencilSimple',
  Trash01: 'Trash',
  XClose: 'X',
  RefreshCw01: 'ArrowCounterClockwise',
  Copy01: 'Copy',
  Repeat01: 'Repeat',
  FilterLines: 'Funnel',
  DotsGrid: 'DotsSixVertical',
  SwitchVertical01: 'ArrowsDownUp',
  SwitchHorizontal01: 'ArrowsLeftRight',
  DotsVertical: 'DotsThreeVertical',
  DotsHorizontal: 'DotsThree',
  ChevronDown: 'CaretDown',
  ChevronUp: 'CaretUp',
  ChevronSelectorVertical: 'CaretUpDown',
  ChevronLeft: 'CaretLeft',
  ChevronRight: 'CaretRight',
  CornerDownRight: 'ArrowElbowDownRight',
  CreditCard01: 'CreditCard',
  InfoCircle: 'Info',
  HelpCircle: 'Question',
  AlertTriangle: 'Warning',
  AlertCircle: 'WarningCircle',
  Shield01: 'Shield',
  UserCheck01: 'UserCheck',
  Mail01: 'Envelope',
  Lock01: 'Lock',
  Key01: 'Key',
  LogIn01: 'SignIn',
  LogOut01: 'SignOut',
  Truck01: 'Car',
  Building01: 'Buildings',
  ShoppingBag01: 'ShoppingBag',
  ShoppingCart01: 'ShoppingCart',
  Monitor01: 'Monitor',
  Phone01: 'DeviceMobile',
  Laptop01: 'Laptop',
  Tablet01: 'DeviceTablet',
  Tv01: 'Television',
  Cloud01: 'Cloud',
  DownloadCloud01: 'CloudArrowDown',
  UploadCloud01: 'CloudArrowUp',
  Download01: 'DownloadSimple',
  Upload01: 'UploadSimple',
  Camera01: 'Camera',
  Image01: 'Image',
  MusicNote01: 'MusicNotes',
  Microphone01: 'Microphone',
  MessageSquare01: 'ChatCircle',
  Briefcase01: 'Briefcase',
  Tool01: 'Wrench',
  Fingerprint01: 'Fingerprint',
  Map01: 'MapTrifold',
  Users01: 'Users',
  User01: 'User',
  UserPlus01: 'UserPlus',
  CpuChip01: 'Cpu',
  Bell01: 'Bell',
  Globe01: 'Globe',
  Translate01: 'Translate',
  AlarmClock: 'Alarm',
  ClockRewind: 'ClockCounterClockwise',
  MedicalCross: 'FirstAidKit',
  MedicalCircle: 'Pill',
  GamingPad01: 'GameController',
  Gift01: 'Gift',
  Lightbulb01: 'Lightbulb',
  Stars01: 'Sparkle',
  Star01: 'Star',
  BatteryCharging01: 'BatteryCharging',
  Columns01: 'Columns',
  Inbox01: 'Envelope',
  Clipboard: 'ClipboardText',
  Ticket01: 'Ticket',
  GraduationHat01: 'GraduationCap',
  Compass01: 'Compass',
  Target01: 'Target',
  PuzzlePiece01: 'PuzzlePiece',
  Share01: 'ShareNetwork',
  LayersThree01: 'Stack',
  Link01: 'Link',
  Award01: 'Medal',
  LinkExternal01: 'ArrowSquareOut',
  Save01: 'FloppyDisk',
  Send01: 'PaperPlaneRight',
  PlusCircle: 'PlusCircle',
  CursorClick01: 'Cursor',
  AtSign: 'At',
  ArrowCircleDown: 'ArrowCircleDown',
  ArrowCircleUp: 'ArrowCircleUp',
  Menu01: 'List',
  MagicWand01: 'MagicWand',
};

export interface IconProps extends Omit<PhosphorIconProps, 'color'> {
  name?: string;
  className?: string;
  size?: number | string;
  color?: string;
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
  title?: string;
  strokeWidth?: number | string;
  style?: React.CSSProperties;
}

export const Icon: React.FC<IconProps> = ({
  name,
  className = '',
  size,
  color = 'currentColor',
  weight = 'duotone',
  style,
  ...props
}) => {
  if (!name) return null;

  // Resolve component name from map or direct match
  const cleanName = name.trim();
  const pascalName = cleanName.replace(/(^[a-z]|[_\-\s]+([a-z0-9]))/gi, (_, p1, p2) => (p2 || p1).toUpperCase());

  const resolvedKey =
    ICON_NAME_MAP[cleanName] ||
    ICON_NAME_MAP[cleanName.toLowerCase()] ||
    ICON_NAME_MAP[pascalName] ||
    cleanName;

  const resolvedPascalKey = resolvedKey.replace(/(^[a-z]|[_\-\s]+([a-z0-9]))/gi, (_, p1, p2) => (p2 || p1).toUpperCase());

  const IconComponent =
    ICONS[resolvedPascalKey] ||
    ICONS[resolvedKey] ||
    ICONS[pascalName] ||
    ICONS[cleanName] ||
    ICONS.SquaresFour;

  // Standardize sizing: If no explicit width/height in className or size prop, default to inline text scaling (1em x 1em)
  const hasWidthClass = /\b(w-\d+|w-\[.*\]|w-full|w-screen|w-auto|size-\d+|size-\[.*\])\b/.test(className);
  const hasHeightClass = /\b(h-\d+|h-\[.*\]|h-full|h-screen|h-auto|size-\d+|size-\[.*\])\b/.test(className);

  const defaultSizeClass = !hasWidthClass && !hasHeightClass && !size ? 'w-[1em] h-[1em] inline-block shrink-0 align-middle' : '';

  return (
    <IconComponent
      className={`${defaultSizeClass} ${className}`.trim()}
      size={size}
      weight={weight}
      color={color}
      style={style}
      {...props}
    />
  );
};

export default Icon;
