name: Docker Image CI/CD
on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  # This resolves to your GitHub username/repository name (e.g., myuser/crystal)
  BASE_IMAGE_NAME: ${{ github.repository }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Tag (Version)
        id: meta
        run: |
          # Extracts the version number (e.g., v1.0.1)
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT 

      # --- Build and Push Backend Image (Tagged with :backend-...) ---
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:backend-${{ steps.meta.outputs.VERSION }}
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:backend-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Build and Push Frontend Image (Tagged with :frontend-...) ---
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:frontend-${{ steps.meta.outputs.VERSION }}
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:frontend-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
